name: Tapes
run-name: Generate Gif Tapes
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.0' # The Go version to download (if necessary) and use.
      - run: echo "🚀 go version $(go version) is installed."
      - run: |
          sudo mkdir -p /etc/apt/keyrings
          sudo curl -fsSL https://repo.charm.sh/apt/gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/charm.gpg
          echo "deb [signed-by=/etc/apt/keyrings/charm.gpg] https://repo.charm.sh/apt/ * *" |  sudo tee /etc/apt/sources.list.d/charm.list
          apt update && apt install vhs ffmpeg
          go install github.com/conneroisu/stubbafet@latest
      - run: vhs ./tapes/pytorch.tape
      - run: echo "🍏 This job's status is ${{ job.status }}."
